### ISSUE TITLE
MVP: User Auth

### ISSUE THREAD

**Issue by forestwelch** [nwelchr/Test_Readme#7]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by wongshington** [comment]
- [x] it isn't recognizing that I am inputting an email address even when I try and signup with all the credentials
- [x] I also think it reads the username from the email input field because that error runs if i leave that field blank
- [x] should be able to navigate back to original site landing page if don't want to log in

**Comment by wongshington** [comment]
- [x] demo user button from the session forms
